version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/blog-jj1lfc-dev'
    schedule:
      interval: 'daily'
    target-branch: 'dev'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'dev'
