services:
  blog-jj1lfc-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-jj1lfc-dev
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./blog-jj1lfc-dev:/app
    working_dir: /app
    stdin_open: true
    environment:
      - NODE_ENV=development
      - REACT_APP_ENV_PROD=false

